export enum Typography {
  body = 'body',
  body2 = 'body2',
  h1 = 'headline1',
  h2 = 'headline2',
  h3 = 'headline3',
  h4 = 'headline4',
  h5 = 'headline5',
  h6 = 'headline6',
  subtitle1 = 'subtitle1',
  subtitle2 = 'subtitle2',
  button = 'button',
  overline = 'overline',
  caption = 'caption',
}
